### ISSUE TITLE
event coordinates are relative to window not containing div

### ISSUE THREAD

**Issue by stufisher** [uglymol/uglymol#1]
If you embed uglymol rather than use a full width / height div then coordinates for actions such as double click are wrong. They need to be corrected for the element position

**Comment by wojdyr** [comment]
How to reproduce it? When I try it on
http://uglymol.github.io/dual.html
it seems to work.

**Comment by stufisher** [comment]
Will make you a test case :)

**Comment by wojdyr** [comment]
I suppose it can be closed?
