### ISSUE TITLE
Larger density map area

### ISSUE THREAD

**Issue by costcohotdog** [uglymol/uglymol#13]
Fantastic tool, thank you! Is there a way to make the density map box larger? I'm forced to pan around a lot since it's quite small.

**Comment by wojdyr** [comment]
try `]` and `[` on keyboard

**Comment by costcohotdog** [comment]
Wow, thank you! I have trouble reading the help :)

Also found where to change the default setting for users.

Thanks again for your quick response and wonderful tool!
