### ISSUE TITLE
pass arguments to xhr for load load_pdb, etc?

### ISSUE THREAD

**Issue by stufisher** [uglymol/uglymol#2]
Would it be possible to pass arguments from load_pdb, load_file through to the xhr object? I need to pass an authorisation token as a header to the xhr request.

**Comment by wojdyr** [comment]
Yes, makes sense. I assume I need to call XMLHttpRequest.setRequestHeader()?
How to you want to name the arguments that are to be passed to XHR?

**Comment by stufisher** [comment]
i guess something like
`load_pdb(file, { requestheaders: { headername: value } })`
which translates to
`req.setRequestHeader(headername,value)`

**Comment by wojdyr** [comment]
in the end I added it as a property of Viewer, so it doesn't need to be specified for all requests. I tested it quickly, seems to work:
```diff
     V = new UM.Viewer({viewer: "viewer", hud: "hud", help: "help"});
+    V.xhr_headers = {hey:'ho'};
     V.load_pdb("data/1mru.pdb");
     V.load_ccp4_maps("data/1mru.map", "data/1mru_diff.map");
```

**Comment by stufisher** [comment]
Many thanks!
