### ISSUE TITLE
Spherical electron density?

### ISSUE THREAD

**Issue by stufisher** [uglymol/uglymol#3]
Request from beamline staff:

> As title, uglymol in ispyb currently displays a slab of density around a point rather than a sphere. The view range is quite narrow and a spherical area of density (like coot) would be more useful when looking at experimental maps.

**Comment by wojdyr** [comment]
Just to make sure I understand it: what is meant by "The view range is quite narrow"? That the "radius" of displayed density is small?

**Comment by wojdyr** [comment]
Coot used to show the density in cube (or parallelepiped?), and then it switched to sphere. I vaguely remember people complaining about it, so I don't know what is preferred. If there is a broad consensus that sphere is better I can switch to sphere.
Could you clarify what was meant by the view range?

**Comment by neil-i03** [comment]
It expands when using ']', but expands along all axes. By the time you have the short axis at a decent coverage, the longer axes cover a huge area. I had it up at radius 40 and it was getting a little unresponsive.

**Comment by wojdyr** [comment]
Thanks for the details. Something must be wrong in UglyMol. I'll try to fix it next week.
Can I find a similar structure in PDB?

**Comment by neil-i03** [comment]
That map/model was from user data but I'll ask if I can share. I had a look at some other map/models from another system and they seem much more like a cube in the display. Only thing that is slightly unusual about the first map was the P1 symmetry, but not sure that would affect the electron density display size.

**Comment by neil-i03** [comment]
I’ve got permission from the data owner to share the map with you, where is the best place to send it to?

**Comment by wojdyr** [comment]
Thanks for reporting it.
I fixed it, more or less. The density is still shown as a parallelepiped, but at least with equal sides.
If it still doesn't look good in some cases - let me know.
