### ISSUE TITLE
reciprocal viewer accepts .json but not .json.gz

### ISSUE THREAD

**Issue by Anthchirp** [uglymol/uglymol#5]
The reciprocal viewer happily accepts .json but not .json.gz.

**Comment by Anthchirp** [comment]
Example file: [rlp.json.gz](https://github.com/uglymol/uglymol/files/2154687/rlp.json.gz)

**Comment by wojdyr** [comment]
That's true. If you use drag-and-drop there is not way to use built-in browser's gzip support to uncompress the file. If you'd access a file on the server, the compression is negotiated between the server and the browser. Normally json files are compressed and uncompressed transparently.

Good to know that someone is trying the reciprocal viewer. I plan to get back to this project soon.
