### ISSUE TITLE
Specify different colors for overlaid structures

### ISSUE THREAD

**Issue by JBGreisman** [uglymol/uglymol#7]
I've been playing around with uglymol, and I was wondering whether it is possible to specify colors for different loaded PDBs. I'm trying to present a time-resolved difference map which I would like to overlay with the "ground" and "excited" state structures. Here's the snippet I am using to load the two PDBs, and change the color of the carbons:

```javascript
V1 = new UM.Viewer({viewer: "viewer1", focusable: true});
V1.load_pdb("https://files.rcsb.org/download/3UME.pdb");
V1.load_pdb("https://files.rcsb.org/download/2PHY.pdb");
V1.config.colors.C = new UM.Color(0x8B0000)
```
This produces the following:
<img src="https://user-images.githubusercontent.com/6944142/93645604-5b64c300-f9d2-11ea-93a0-8d3022db2777.png" width="300"/>

Although the two structures have different colors, I would like to specify the colors used for each PDB. Is there an easy way to do this with ``uglymol``? Looking at the js for the ``Viewer``, I haven't quite figured out if it's possible to specify colors in a way other than the global `Viewer.config.colors` settings -- can they be specified for each PDB separately?

Thanks for your help!
Jack

**Comment by wojdyr** [comment]
Hi Jack,

the colors of C in the second and next models are calculated by changing hue of the base color.
You can change the color by changing `hue_shift`:

    V1.model_bags[1].hue_shift = 0.3

(you can't change the brightness and saturation this way, though)

**Comment by JBGreisman** [comment]
I may be using this incorrectly, but the following snippet produces a TypeError for me:

```javascript
V1 = new UM.Viewer({viewer: "viewer1", focusable: true}); 
V1.load_pdb("https://files.rcsb.org/download/3UME.pdb");  
V1.load_pdb("https://files.rcsb.org/download/2PHY.pdb");  
V1.model_bags[1].hue_shift = 0.3;                         
```
This produces the following error in the console:
``Uncaught TypeError: Cannot set property 'hue_shift' of undefined at dual.html:65``

Is there a different way that one is meant to index into the `model_bags` Array?

**Comment by wojdyr** [comment]
`load_pdb()` is asynchronous.
See https://github.com/uglymol/uglymol/wiki#how-to-add-it-to-my-website
You'd need to set hue_shift in a callback.

**Comment by JBGreisman** [comment]
Awesome -- thanks! I hadn't fully grokked the implication of the asynchronous loading.

I'm going to close this because I can now accomplish my use case. The final snippet is as follows -- it was also necessary to add a call to `redraw_models()` in order to have the change to `hue_shift` take effect.
```javascript
 V1 = new UM.Viewer({viewer: "viewer1", focusable: true});
 V1.config.colors.C = new UM.Color(0x8B0000)
 V1.config.water_style = "invisible"
 V1.load_pdb("https://files.rcsb.org/download/2PHY.pdb");
 V1.load_pdb("https://files.rcsb.org/download/3UME.pdb", null, function () {
     V1.model_bags[1].hue_shift = 0.4;
     V1.redraw_models();
 });
```

**Comment by wojdyr** [comment]
it's not guaranteed that 2PHY will get loaded before 3UME, so if you'd like to be sure you could do:
```js
V1.load_pdb("https://files.rcsb.org/download/2PHY.pdb", null, function() {
    V1.load_pdb("https://files.rcsb.org/download/3UME.pdb", null, function () {
```
